version: '3.8'
networks:
  netmagnum:
    driver: bridge
services:      
  database:
    container_name: database
    image: mysql/mysql-server:8.0
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: d_influencer
        MYSQL_USER: dinfluser
        MYSQL_PASSWORD: g2(*3f-02_9pu
    ports:
        - "9907:3306"
    volumes:
        - ./DB:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - netmagnum
  client:
    container_name: client
    build:
      context: .
      target: frontend
      dockerfile: front-end/Dockerfile
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./front-end/www:/usr/src/app
    links:
      - server
    networks:
      - netmagnum
  server:
    container_name: server
    image: nginx:latest
    depends_on:
      - api
    ports:
      - '8000:80'
    volumes:
      - ./back-end/www:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - api
    networks:
      - netmagnum
  api:
    container_name: api
    build:
      context: ./
      dockerfile: back-end/Dockerfile
    depends_on:
      database:
        condition: service_healthy    
    links:
      - database
    volumes:
      - ./back-end/www:/var/www
    networks:
      - netmagnum